### ISSUE TITLE
Great Plugin!!

### ISSUE THREAD

**Issue by M2RE** [MrBertie/jwlib-linker#1]
Hey Brother!
Greetings from United States.

You did a great job adding this plugin, it was needed. I was searching and really scratching my head trying to find a way to use obsidian to open Bible links and came across your plugin. I have my Pioneer School coming up and was wondering if Spanish would be a language you are willing to add to the plugin recognition for the bible text, not the full program. I love Obsidian and JWLibrary, having a link to both would be awesome in the school.

Thanks your your hard work!

**Comment by MrBertie** [comment]
Thank you for the compliment! I'm glad you find it useful also. 

Yes, I have already started adding support for multiple languages (I also speak French, German and Malagasy...), just haven't had time to finish and test it. I'm also not 100% sure how to distinguish between the scripture reference language if it is ambiguous... Still working on the UI/UX for that. Suggestions are welcomed.

Is there an easy way for me to contact you privately if you would prefer that?

**Comment by M2RE** [comment]
Hello, yes my email is: 

jvelez460@gmail.com

I have a few lines of code that can help to add the Spanish recognition. 

Also the commands are not showing whenI add the plugin. Neither plugin settings.

**Comment by MrBertie** [comment]
Try the latest version and see if you still have problems with the commands not showing.  As for Spanish language I will eventually get to adding multi language support but only later this year when I get more time.

**Comment by ClassicVintage** [comment]
Let me know when you do add support for multiple languages. I might be able to supply Chinese Mandarin.
