### ISSUE TITLE
Only 1 command?

### ISSUE THREAD

**Issue by dubefab** [MrBertie/jwlib-linker#2]
Hi,

I love the app, but I’m wondering if something might be missing. I don’t see any settings to choose from, and when I invoke commands, the only one that shows up is "convert to JWL link"—none of the others.

Also, would it be possible to add support for parsing other books like OD, SFL, LFF, etc.?

Thanks!

**Comment by MrBertie** [comment]
1. I'm not sure what is causing only one command to show up. I'm in the middle of updating ready for another release so I'll check on that as well.
2. "other books..." Do you mean creating JW Library links for book references just like with bible references? I.e. if you write a valid SFL reference then it would automatically link it to the correct JW Library publication?  Is so, yes I will eventually get to that.  It all takes time and I only get a little each week for programming!
3. I'm also looking into fetching the results of a wol.jw.org publication reference lookup.

**Comment by dubefab** [comment]
1. No idea... I have that folder with the files form your release in there, and only that convert one works...
2. Yes, if I could be in reading view and could click sfl 2:1 for example, that would be great!
3. Awesome

**Comment by MrBertie** [comment]
Try the latest version and see if it solves the missing commands problem.
The publication reference lookup now works as well.
I did look into adding automatic publication lookup like I do for scriptures but the trouble is that the publication reference syntax is arbitrary and varied making it difficult to recognise.  There appear to be no fixed standards as it has changed much over the years.  So I won't be pursuing that for now.
