### ISSUE TITLE
Unable to adjust ‘No. of words inline’

### ISSUE THREAD

**Issue by scaldo11** [MrBertie/jwlib-linker#3]
Hello! 
Loving your plugin! Thanks for developing and sharing. 

I’ve noticed in the plugin settings that I can’t adjust the amount of words using the ‘No. of words inline’ slider.
I can move the slider and it will stay there until I leave settings. When I go back to settings, the slider is back to the default 25 words. I was hoping to increase the amount of words to generally capture an entire verse.

I’ve tried adjusting on MacOS, iPadOS, iOS and Windows 11. Getting the same results on all platforms. 

Thanks!

**Comment by MrBertie** [comment]
Definitely a bug, I've fixed it, a new version will be uploaded soon!  I also added the option to set the value to 0 to make it fetch the entire verse(s)

**Comment by MrBertie** [comment]
This has been fixed in the latest version.
